[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.24'
optimizer_runs = 800
via_ir = false
evm_version = 'cancun'

[profile.default.fuzz]
runs = 1000

[profile.ci.fuzz]
runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
